#!/bin/bash

# Create build-directory
mkdir build

# Move into the build-directory
cd build

# Run CMake to create a Makefile
cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9  ../

# Make the Makefile using two threads
make -j2

# Move the executable to the top-directory
mv vmc ..
