#!/bin/bash
export PMIX_MCA_gds=hash
# Create build-directory
# module r yes_compiled
mkdir build

# Move into the build-directory
cd build

# Run CMake to create a Makefile
# If compiler problems in OS X, add -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9.
#CMAKE_PREFIX_PATH=/cluster/home/oliverlh/parallell_code/armadillo-9.870.2/
cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 ../
# -D=ARMADILLO_INCLUDE_DIR=/cluster/home/oliverlh/parallell_code/include/
# Make the Makefile using two threads
make -j2

# Move the executable to the top-directory
mv vmc ..
