#!/bin/bash

# Job name:
#SBATCH --job-name=VMC
#
# Project:
#SBATCH --account=NN9987K
#
# Wall clock limit:
#SBATCH --time=01:00:00
#
# Max memory usage:
#SBATCH --mem-per-cpu=3800
#
# Specify normal partition
#SBATCH --partition=normal
#
# Number of tasks (MPI ranks):
#SBATCH --ntasks=124
#
# Number of nodes
#SBATCH --nodes=8
#
#
# Send mail with info:
#Nei -SBATCH --mail-type=BEGIN,TIME_LIMIT_10,END

## Set up job environment:

module purge   # clear any inherited modules
set -o errexit # exit on errors

#module load OpenMPI/4.0.3-GCC-9.3.0
#module load GCC/9.3.0
#module load CMake/3.16.4-GCCcore-9.3.0 
module r yes_compiled

mpirun ./vmc  
